apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw1
  labels:
    app: hw1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw1
  template:
    metadata:
      labels:
        app: hw1
    spec:
      containers:
      - name: hw1
        image: 160104030/hw111
        livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 80
            periodSeconds: 10
        readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 80
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hw1-service
spec:
  selector:
    app: hw1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000



